language: cpp
sudo: required
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq liblapack*
        - sudo apt-get install -qq libblas*
        - sudo apt-get install -qq libitpp*
        - sudo apt-get install -qq libfftw3*
        - sudo apt-get install -qq libtclap-dev
#script: ./descargador.sh && make vecs && ./vecs
#script: cd cpp/ && make test_spins && ./test_spins
#script: cd cpp/ && make test_memory_time && ./test_memory_time
script: cd cpp/ && make test_rmt && ./test_rmt
